linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - revive
    - errcheck

run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
